import React from 'react';

import {TUsePlantTreePermissions} from 'utilities/hooks/usePlantTreePermissions';

export const mockPlantTreePermissionsBlocked: TUsePlantTreePermissions = {
  cameraPermission: 'blocked',
  locationPermission: 'blocked',
  userLocation: null,
  checkPermission: () => {},
  requestPermission: () => {},
  checkUserLocation: () => {},
  openPermissionsSettings: (isGranted?: boolean) => {},
  openGpsRequest: (isGranted?: boolean) => {},
  requestCameraPermission: (isGranted?: boolean) => {},
  requestLocationPermission: (isGranted?: boolean) => {},
  isCameraBlocked: true,
  isLocationBlocked: true,
  isCameraGranted: false,
  isLocationGranted: false,
  isGPSEnabled: false,
  hasLocation: false,
  isChecking: false,
  isGranted: false,
  cantProceed: true,
  requested: true,
  showPermissionModal: true,
};

export const mockPlantTreePermissionsChecking: TUsePlantTreePermissions = {
  cameraPermission: null,
  locationPermission: null,
  userLocation: null,
  checkPermission: () => {},
  requestPermission: () => {},
  checkUserLocation: () => {},
  openPermissionsSettings: (isGranted?: boolean) => {},
  openGpsRequest: (isGranted?: boolean) => {},
  requestCameraPermission: (isGranted?: boolean) => {},
  requestLocationPermission: (isGranted?: boolean) => {},
  isCameraBlocked: false,
  isLocationBlocked: false,
  isCameraGranted: false,
  isLocationGranted: false,
  isGPSEnabled: false,
  hasLocation: false,
  isChecking: true,
  isGranted: false,
  cantProceed: false,
  requested: false,
  showPermissionModal: true,
};

export const mockPlantTreePermissionsGranted: TUsePlantTreePermissions = {
  cameraPermission: 'granted',
  locationPermission: 'granted',
  userLocation: {
    latitude: 23213213,
    longitude: 332424324,
  },
  checkPermission: () => {},
  requestPermission: () => {},
  checkUserLocation: () => {},
  openPermissionsSettings: (isGranted?: boolean) => {},
  openGpsRequest: (isGranted?: boolean) => {},
  requestCameraPermission: (isGranted?: boolean) => {},
  requestLocationPermission: (isGranted?: boolean) => {},
  isCameraBlocked: false,
  isLocationBlocked: false,
  isCameraGranted: true,
  isLocationGranted: true,
  isGPSEnabled: true,
  hasLocation: true,
  isChecking: false,
  isGranted: true,
  cantProceed: false,
  requested: true,
  showPermissionModal: false,
};
