import React from 'react';

import {TUsePlantTreePermissions} from 'utilities/hooks/usePlantTreePermissions';
import {OpenSettingsButton} from 'screens/TreeSubmissionV2/components/OpenSettingsButton/OpenSettingsButton';

export const mockPlantTreePermissionsBlocked: TUsePlantTreePermissions = {
  cameraPermission: 'blocked',
  locationPermission: 'blocked',
  userLocation: null,
  checkPermission: () => {},
  requestPermission: () => {},
  checkUserLocation: () => {},
  openPermissionsSettings: (isGranted?: boolean) => {},
  openGpsRequest: (isGranted?: boolean) => {},
  requestCameraPermission: (isGranted?: boolean) => {},
  requestLocationPermission: (isGranted?: boolean) => {},
  isCameraBlocked: true,
  isLocationBlocked: true,
  isCameraGranted: false,
  isLocationGranted: false,
  isGPSEnabled: false,
  hasLocation: false,
  isChecking: false,
  isGranted: false,
  cantProceed: true,
  requested: true,
  showPermissionModal: true,
};

export const mockPlantTreePermissionsChecking: TUsePlantTreePermissions = {
  cameraPermission: null,
  locationPermission: null,
  userLocation: null,
  checkPermission: () => {},
  requestPermission: () => {},
  checkUserLocation: () => {},
  openPermissionsSettings: (isGranted?: boolean) => {},
  openGpsRequest: (isGranted?: boolean) => {},
  requestCameraPermission: (isGranted?: boolean) => {},
  requestLocationPermission: (isGranted?: boolean) => {},
  isCameraBlocked: false,
  isLocationBlocked: false,
  isCameraGranted: false,
  isLocationGranted: false,
  isGPSEnabled: false,
  hasLocation: false,
  isChecking: true,
  isGranted: false,
  cantProceed: false,
  requested: false,
  showPermissionModal: true,
};

export const mockPlantTreePermissionsGranted: TUsePlantTreePermissions = {
  cameraPermission: 'granted',
  locationPermission: 'granted',
  userLocation: {
    latitude: 23213213,
    longitude: 332424324,
  },
  checkPermission: () => {},
  requestPermission: () => {},
  checkUserLocation: () => {},
  openPermissionsSettings: (isGranted?: boolean) => {},
  openGpsRequest: (isGranted?: boolean) => {},
  requestCameraPermission: (isGranted?: boolean) => {},
  requestLocationPermission: (isGranted?: boolean) => {},
  isCameraBlocked: false,
  isLocationBlocked: false,
  isCameraGranted: true,
  isLocationGranted: true,
  isGPSEnabled: true,
  hasLocation: true,
  isChecking: false,
  isGranted: true,
  cantProceed: false,
  requested: true,
  showPermissionModal: false,
};

export const mockPlantTreePermissionsLocationGranted: TUsePlantTreePermissions = {
  cameraPermission: 'blocked',
  locationPermission: 'granted',
  userLocation: {
    latitude: 23213213,
    longitude: 332424324,
  },
  checkPermission: () => {},
  requestPermission: () => {},
  checkUserLocation: () => {},
  openPermissionsSettings: (isGranted?: boolean) => {},
  openGpsRequest: (isGranted?: boolean) => {},
  requestCameraPermission: (isGranted?: boolean) => {},
  requestLocationPermission: (isGranted?: boolean) => {},
  isCameraBlocked: true,
  isLocationBlocked: false,
  isCameraGranted: false,
  isLocationGranted: true,
  isGPSEnabled: true,
  hasLocation: true,
  isChecking: false,
  isGranted: false,
  cantProceed: true,
  requested: true,
  showPermissionModal: true,
};

export const mockPlantTreePermissionsCameraGranted: TUsePlantTreePermissions = {
  cameraPermission: 'granted',
  locationPermission: 'blocked',
  userLocation: {
    latitude: 23213213,
    longitude: 332424324,
  },
  checkPermission: () => {},
  requestPermission: () => {},
  checkUserLocation: () => {},
  openPermissionsSettings: (isGranted?: boolean) => {},
  openGpsRequest: (isGranted?: boolean) => {},
  requestCameraPermission: (isGranted?: boolean) => {},
  requestLocationPermission: (isGranted?: boolean) => {},
  isCameraBlocked: false,
  isLocationBlocked: true,
  isCameraGranted: true,
  isLocationGranted: false,
  isGPSEnabled: true,
  hasLocation: false,
  isChecking: false,
  isGranted: false,
  cantProceed: true,
  requested: true,
  showPermissionModal: true,
};

export const mockBlockedAllPermissions = [
  {
    name: 'checkPermission.permissions.location',
    status: <OpenSettingsButton caption={'checkPermission.grantNow'} onPress={() => {}} />,
    onPress: () => {},
    icon: 'md-location-outline',
    isExist: true,
    isGranted: false,
  },
  {
    name: 'checkPermission.permissions.camera',
    status: <OpenSettingsButton caption={'checkPermission.grantNow'} onPress={() => {}} />,
    onPress: () => {},
    icon: 'camera-outline',
    isExist: true,
    isGranted: false,
  },
  {
    name: 'checkPermission.permissions.GPS',
    status: <OpenSettingsButton caption={'checkPermission.turnOn'} onPress={() => {}} />,
    onPress: () => {},
    icon: 'locate',
    isExist: true,
    isGranted: false,
  },
];

export const mockCheckingAllPermissions = [
  {
    name: 'checkPermission.permissions.location',
    status: 'checkPermission.dottedChecking',
    onPress: () => {},
    icon: 'md-location-outline',
    isExist: false,
    isGranted: false,
  },
  {
    name: 'checkPermission.permissions.camera',
    status: 'checkPermission.dottedChecking',
    onPress: () => {},
    icon: 'camera-outline',
    isExist: false,
    isGranted: false,
  },
  {
    name: 'checkPermission.permissions.GPS',
    status: 'checkPermission.dottedChecking',
    onPress: () => {},
    icon: 'locate',
    isExist: false,
    isGranted: false,
  },
];

export const mockBlockedOnePermissions = [
  {
    name: 'checkPermission.permissions.location',
    status: <OpenSettingsButton caption={'checkPermission.grantNow'} onPress={() => {}} />,
    onPress: () => {},
    icon: 'md-location-outline',
    isExist: false,
    isGranted: false,
  },
  {
    name: 'checkPermission.permissions.camera',
    status: 'checkPermission.granted',
    onPress: () => {},
    icon: 'camera-outline',
    isExist: true,
    isGranted: true,
  },
  {
    name: 'checkPermission.permissions.GPS',
    status: 'checkPermission.enabled',
    onPress: () => {},
    icon: 'locate',
    isExist: true,
    isGranted: true,
  },
];

export const mockBlockedTwoPermissions = [
  {
    name: 'checkPermission.permissions.location',
    status: <OpenSettingsButton caption={'checkPermission.grantNow'} onPress={() => {}} />,
    onPress: () => {},
    icon: 'md-location-outline',
    isExist: false,
    isGranted: false,
  },
  {
    name: 'checkPermission.permissions.camera',
    status: <OpenSettingsButton caption={'checkPermission.grantNow'} onPress={() => {}} />,
    onPress: () => {},
    icon: 'camera-outline',
    isExist: false,
    isGranted: false,
  },
  {
    name: 'checkPermission.permissions.GPS',
    status: 'checkPermission.enabled',
    onPress: () => {},
    icon: 'locate',
    isExist: true,
    isGranted: true,
  },
];

export const mockGrantedAllPermissions = [
  {
    name: 'checkPermission.permissions.location',
    status: 'checkPermission.granted',
    onPress: () => {},
    icon: 'md-location-outline',
    isExist: true,
    isGranted: true,
  },
  {
    name: 'checkPermission.permissions.camera',
    status: 'checkPermission.granted',
    onPress: () => {},
    icon: 'camera-outline',
    isExist: true,
    isGranted: true,
  },
  {
    name: 'checkPermission.permissions.GPS',
    status: 'checkPermission.enabled',
    onPress: () => {},
    icon: 'locate',
    isExist: true,
    isGranted: true,
  },
];
