export const notVerifiedTreesMock = [
  {
    _id: '1',
    signer: 'string',
    nonce: 2,
    treeSpecs: JSON.stringify({location: {latitude: 2000000, longitude: 213213123123}}),
    signature: 'string',
    status: 2,
    createdAt: 'string',
    updatedAt: 'string',
  },
  {
    _id: '2',
    signer: 'string',
    nonce: 2,
    treeSpecs: JSON.stringify({location: {latitude: 2000000, longitude: 213213123123}, nursery: true}),
    birthDate: 2,
    countryCode: 2,
    treeId: 5,
    signature: 'string',
    status: 2,
    createdAt: 'string',
    updatedAt: 'string',
  },
  {
    _id: '2',
    signer: 'string',
    nonce: 2,
    treeSpecs: 'string',
    treeId: 5,
    signature: 'string',
    status: 2,
    createdAt: 'string',
    updatedAt: 'string',
  },
  {
    _id: '2',
    signer: 'string',
    nonce: 2,
    treeSpecs: JSON.stringify({location: {latitude: 2000000, longitude: 213213123123}}),
    treeId: 5,
    signature: 'string',
    status: 2,
    createdAt: 'string',
    updatedAt: 'string',
  },
];
